# Generated by Django 5.0.6 on 2024-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='task',
            name='authors',
            field=models.ManyToManyField(related_name='assigned_tasks', to='tasks.author'),
        ),
    ]
